### ISSUE TITLE
failed to build

### ISSUE THREAD

**Issue by gaborbernat** [etsy/Hound#10]
src/hound/index/grep.go:64: function ends without a return statement
src/hound/index/grep.go:137: function ends without a return statement

**Comment by jklein** [comment]
Can you post the version of Go you are using, and what OS you are trying to build Hound on? Also the command you used to get this error would be helpful as well.

**Comment by statwonk** [comment]
Mine also failed with:

```
username:Hound (master*) $ ./bin/houndd
panic: invalid character '}' looking for beginning of object key string

goroutine 1 [running]:
main.main()
        /Users/username/Hound/src/hound/cmds/houndd/main.go:299 +0x536
```

**Comment by jklein** [comment]
@statwonk can you paste your config?

**Comment by yifu** [comment]
Hi @jklein same issue for me here:

````
$ go run src/hound/cmds/houndd/main.go 
panic: invalid character '}' looking for beginning of object key string


goroutine 1 [running]:
main.main
	/home/ybaumes/Hound/src/hound/cmds/houndd/main.go:299
exit status 2
````

And here is my 'go' cfg:
```
$ go version
go version xgcc (Ubuntu 4.9.1-0ubuntu1) 4.9.1 linux/amd64
```

Do you need more information?

**Comment by yifu** [comment]
@jklein ok got it. I just remove a comma from my json file. It works now.. Sorry for the noise.

**Comment by jklein** [comment]
Yup makes sense @yifu, and @statwonk I bet you are having the same issue. @gaborbernat your problem sounds like it might be different. Go version, `config.json`, and OS info would be helpful.

**Comment by gaborbernat** [comment]
go version go1.0.2, 
Debian GNU/Linux 7 \n \l :) 
default config file

**Comment by jklein** [comment]
We don't support go versions below 1.3, sorry. If you find an issue with the latest version of Go please open another issue.
