### ISSUE TITLE
Install with go

### ISSUE THREAD

**Issue by tnguyen14** [etsy/Hound#100]
I tried following the instruction by doing the following:

```
git clone git@github.com:etsy/Hound.git
cd Hound
go get github.com/etsy/hound/cmds/houndd
houndd
```

However, I got this error `bash: houndd: command not found`. I am not familiar with go at all, so I am not sure what I am doing wrong. Could someone point me in the right direction?

**Comment by kellegous** [comment]
When you do `go get`, go installs the binaries in `$GOPATH/bin`. The best guide on this is the [Workspaces section of How to Write Go Code](https://golang.org/doc/code.html#Workspaces). If you just want to run Hound, you can do the following:
```
mkdir Hound
cd Hound
GOPATH=`pwd` go get github.com/etsy/hound/cmds/...
# make sure you setup a config.json file
./bin/houndd
```

BTW, which instructions are you following? I would love to update them.

**Comment by tnguyen14** [comment]
Thanks! I just followed your guide above and that worked fine. I didn't understand and I could install houndd as a system package and call it anywhere with the $GOPATH defined. I didn't have my $GOPATH defined.
Your instruction is an interesting way to install and run it in a local directory as well, which is nice and contained.

I was following the guide on the README, but I didn't understand it because I didn't have context. The commands `mkdir Hound; cd Hound;` and setting GOPATH to `pwd` really helped. I was also confused by the triple dots `...` at the end of the get command - I thought I was supposed to put something there on my own.
