### ISSUE TITLE
Allow pushing updates instead of polling

### ISSUE THREAD

**Issue by jnackman** [etsy/Hound#111]
For a large number of repos, it would be nice to be able to turn off polling and hit an API endpoint to update the indexes instead.  This would reduce unnecessary traffic and keep results more recent.

I have an implementation of this that I can submit a PR for if this seems reasonable.

**Comment by Lafriks** [comment]
This would be great feature

**Comment by kellegous** [comment]
Thanks to @jnackman, this is a supported feature now on HEAD.
