### ISSUE TITLE
Error: too many open files after indexing large number of repos

### ISSUE THREAD

**Issue by ibam** [etsy/Hound#113]
We tried using Hound on our company's codebase, but there seem to be an upper limit to the number of repos or the size of codebase that Hound can handle. In our case, we are indexing ~250 repos containing a combined total of millions of LOCs, and Hound (or the underlying Go) emitted the following error when we tried to execute a search:

> ERROR:open /Users/iarief/workspace/hackathon-april2015/hound/data/idx-7e26ac6530283f3e/raw/content.txt: too many open files

The total size of the data folder is about 5.5 GB when compressed. Is this beyond the known practical upper limit of Hound?

**Comment by kellegous** [comment]
With that many repos, you have have to tweak your file descriptor limits. I'm really curious what your current limit is?

From the same login you run Hound, what do these commands report?
`ulimit -Sn`
`ulimit -Hn`

The searchers are currently setup to be pretty aggressive in terms of parallelism ... we can probably put a practical limit on that to avoid opening so many files simultaneously when working on a large repo list.

**Comment by kellegous** [comment]
I setup a test this weekend with 1k repositories and what I'm finding is that I can execute searches just fine without exhausting the file descriptors limit (1024) so long as no indexing is happening. When the searchers are trying to update simultaneously (especially if they are running git), I hit issues. The right answer here, I think, is to actually throttle indexing to ensure that no more than N searchers are reindexing at a time.
