### ISSUE TITLE
Direct links to Bitbucket source files are broken for SSH URLs

### ISSUE THREAD

**Issue by jawshooah** [etsy/Hound#124]
I have an SSH-style URL for a private Bitbucket repository. Let's say it's

```
git@bitbucket.org:JoshHagins/foo.git
```

The direct links generated by Hound take the form 

```
https://bitbucket.org/JoshHagins/foo/blob/master/foo.sh
```

This leads to a "404: Oops, you've found a dead link" page. The correct form is

```
https://bitbucket.org/JoshHagins/foo/src/<commit-hash>/foo.sh?at=master
```

**Comment by jklein** [comment]
Is the commit hash required? If not, the url-pattern option should help: 

https://github.com/etsy/Hound/blob/master/config-example.json#L38-L44

**Comment by jawshooah** [comment]
Ah, somehow missed that. Works with the following config:

```json
{
  "Foo": {
    "url": "git@bitbucket.org:JoshHagins/foo.git",
    "url-pattern": {
      "base-url": "{url}/src/master/{path}{anchor}",
      "anchor": "#cl-{line}"
    }
  }
}
```

Thanks!
