### ISSUE TITLE
How to include credential in GitRepo config

### ISSUE THREAD

**Issue by suchangming** [etsy/Hound#126]
Seems config-examples.jason only provides session for SVN with creds. 

How to modify for Git? Thanks.

"SomeGitRepo" : {
            "url" : "http://server/scm/project/repo.git",
            "vcs-config" : {
                "username" : "username_for_ro_account",
                "password" : "password_for_ro_account"
            }
        }

**Comment by jklein** [comment]
What are you trying to do? If you want to index a private Git repo you can follow the instructions here:

https://github.com/etsy/Hound#private-repositories

**Comment by jklein** [comment]
I'm going to close this, let us know if you still have an issue here.
