### ISSUE TITLE
Indexed files removed by other repos

### ISSUE THREAD

**Issue by adstephenson** [etsy/Hound#14]
When searching I received errors of the form:

`ERROR:open <path to missing file>: no such file or directory`

I think this is due to the [expungeOldIndexes](https://github.com/etsy/Hound/blob/master/src/hound/searcher/searcher.go#L49) function in searcher.go 
If, for example, you have two projects: 'my-project' and 'my-project-tests', indexing of 'my-project' removes directories matching 'my-project-', which includes the directories for 'my-project-tests'.

**Comment by jklein** [comment]
Interesting, yeah this looks like a legitimate bug. Thanks for reporting it.

**Comment by jklein** [comment]
Fixed by that commit ^^

**Comment by adstephenson** [comment]
Thanks for the quick response. Unfortunately I'm getting the same problem.

An example directory structure:
1 - my-project
2 - my-project-[HASH]
3 - my-project-tests
4 - my-project-tests-[HASH]

The regex matches 2 and 4 so they are both removed. 
I think updating the regex to include the directory name would fix it. Something like:
```
pat := regexp.MustCompile(fmt.Sprintf("%s-[0-9a-f]{40}$",gitDir))
```
works for my example, but would need to confirm that special characters in gitDir don't break the regexp.
