### ISSUE TITLE
Hover hint on button next to search hits.

### ISSUE THREAD

**Issue by vext01** [etsy/Hound#16]
Hey,

What does the button next to each hit do? Can you add some mouseover text so we know.

Looks like a clipboard. Is it "copy to clipboard"? Doesn't seem to work if so.

Thanks

**Comment by jklein** [comment]
It does copy to the clipboard. It requires flash, so perhaps you are blocking that somehow?

**Comment by vext01** [comment]
I don't have flash installed.

**Comment by jklein** [comment]
That would be the problem then. I'm going to close this and open an issue for hiding that button if flash isn't present.

**Comment by vext01** [comment]
Thanks!
