### ISSUE TITLE
Can't build hound on Ubuntu 15.04 due to missing jsx

### ISSUE THREAD

**Issue by sturmf** [etsy/hound#163]
I can't build on Ubutu 15.04 due to missing jsx. I installed it with "npm install jsx" but now I get the following output:

sturm@yoga:~/src/hound/src/github.com/etsy/hound$ make
rsync -r --exclude '*.js' ui/assets/* .build/ui
jsx --no-cache-dir ui/assets/js .build/ui/js
Makefile:8: recipe for target 'ui/bindata.go' failed
make: *** [ui/bindata.go] Error 1

Any ideas?

**Comment by sturmf** [comment]
One reason seems to be $(shell pwd) not supported by the standard shell in Ubunut. But changing it to `pwd`only gets me a tiny step further. The step still fails with the same output.

**Comment by kellegous** [comment]
One of the issues is that you installed https://www.npmjs.com/package/jsx instead of https://www.npmjs.com/package/react-tools. Don't run `npm install jsx`, you want react-tools, `npm install react-tools`. It's confusing, I know. Someone had the name jsx before react was created, sadly.

**Comment by sturmf** [comment]
Thanks for the clarification. Unfortunately jsx from react-tools also doesn't work.

**Comment by jklein** [comment]
FWIW, react-tools is now deprecated in favor of Babel:

https://facebook.github.io/react/blog/2015/06/12/deprecating-jstransform-and-react-tools.html

We should probably upgrade React and remove this dependency. If you want to
go down that path and see if it fixes your problem it would be much
appreciated.

**Comment by kellegous** [comment]
Sorry, @sturmf, there isn't enough information in your last comment to know what's going wrong. Perhaps this will help, I am including the Vagrantfile where I confirmed that the build works properly:

```
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/vivid64"
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install --yes golang nodejs npm
    sudo ln -s `which nodejs` /usr/bin/node
    sudo npm install -g react-tools
    git clone https://github.com/etsy/hound.git hound/src/github.com/etsy/hound
    cd hound
    src/github.com/etsy/hound/tools/setup
    make
  SHELL
end
```

**Comment by sturmf** [comment]
A thanks for the instructions, that solved the mystery. I installe "apt-get install node" not knowing that it is something completely different. After removing node I got: /usr/bin/env: node: File or directory not found. And that is solved with your ln -s line.
Maybe that should be added as a hint to the docs.
