### ISSUE TITLE
Change name?

### ISSUE THREAD

**Issue by croaky** [etsy/Hound#18]
Howdy folks,

This project looks cool. Nice idea and execution.

I work at [thoughtbot](http://thoughtbot.com). We've run a product, also called [Hound](https://houndci.com/), for a year or so. It is a hosted Continuous Integration service to check code style on GitHub pull requests. It is also open source.

We've noticed a number of people expressing confusion over the conflicting "Hound" name for code-related tools:

* https://twitter.com/estebanrules/status/560323771308187648
* https://twitter.com/mmwtsn/status/560486602770632704
* https://twitter.com/shawnacscott/status/560379767879237634

Would you mind changing the name of this project to something else?

Happy to chat over email if that's easier, too. <dan@thoughtbot.com>.

Dan

**Comment by jklein** [comment]
@croaky I'll email you, going to close this issue.
