### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by deer-hope** [etsy/hound#180]
nanzhi-MBP:hound nanzhi$ make
mkdir -p build/ui
rsync -r --exclude '*.js' src/github.com/etsy/hound/ui/assets/* build/ui
jsx --no-cache-dir src/github.com/etsy/hound/ui/assets/js build/ui/js
unknown option: --no-cache-dir
make: *** [src/github.com/etsy/hound/ui/bindata.go] Error 1

**Comment by kellegous** [comment]
Thanks. I really need to update the tools associated with react.

**Comment by kellegous** [comment]
@deer-hope What version of react-tools are you using?
```
$ jsx --version
0.13.3
```

**Comment by kellegous** [comment]
Actually, I suspect you installed JSX and not react-tools `npm install react-tools` (not `npm install jsx`)
