### ISSUE TITLE
Cannot click to close the advanced search options

### ISSUE THREAD

**Issue by Wilfred** [etsy/hound#184]
Clicking 'Advanced' opens the advanced options in the web UI. However, clicking the chevron does not close the web UI.

I can work around by focusing on the main search input, which closes the advanced options.

Tested on both Firefox and Chrome.

**Comment by kellegous** [comment]
I'm unable to reproduce this. There is a known issue that the whole Advanced dialog shows the pointer cursor making it really hard to tell when your mouse is over the up chevron. Could this be what is affecting you?

The steps I've tried to reproduce this:
 1. Load hound UI.
 2. Click on "Advanced: Ignore case, filter by path, stuff like that." (advanced dialog slides down)
 3. Immediately click on the up chevron. (advanced dialog slides up)

**Comment by Wilfred** [comment]
Oh, you're absolutely right. If I click the chevron exactly, the advanced dialog closes.

As you said, I was confused because of the point cursor on the whole dialog. Is there a duplicate bug that I can close this against?
