### ISSUE TITLE
Make links in search results work for SSH style repo URLs

### ISSUE THREAD

**Issue by jklein** [etsy/Hound#19]
Currently Hound only supports HTTP style URLs for repos, and it would be nice to support SSH as well.

**Comment by kgodwin** [comment]
https://github.com/etsy/Hound/blob/b0f9b34552cf28357b20f9dfeeac9f532a8c8375/src/hound/git/git.go#L52

{
    "dbpath": "data",
    "repos": {
        "repo": {
            "url": "git@gitlab-install:namespace\/repo.git"
        }
}

I'm pretty sure this does work as I've set it up for an internal gitlab install over SSH. It basically will take any uri that Git would I believe.

**Comment by jklein** [comment]
Yeah it clones, but then all of the links from search results are broken I believe.

**Comment by kgodwin** [comment]
Ah, I misunderstood what you were asking about. There was another user with a similar question and I thought you were asking a similar one.

**Comment by brucestephens** [comment]
If you want to get something working quickly (i.e., hack the code for your site) the thing to change
seems to be `UrlToRepo` in `pub/assets/js/hound.js`. (I'm assuming you've got something like gitweb, cgit, etc., set up to point at.)

**Comment by kgodwin** [comment]
Given Hound already clones things into data/[repo-name] and it operates as a webapp, wouldn't it just make more sense to just self-host the not http:// repos so it just displays the local copy the search index is built on? [e.g. file:///, ssh]

**Comment by brucestephens** [comment]
Just having Hound serve source seems like a good option (and likely would be a useful default when
the URL doesn't look like a github one). More generally it's surely useful to be able to link to
some other service (one that has syntax highlighting, version control or cross referencing).

**Comment by kgodwin** [comment]
Maybe the path forward then is:

If [contains github.com] -> Link as per current
if [UrlToRepo: contains alternative-link-scheme] -> Link as per listed link scheme
else -> Self-serve [with syntax highlighting and links to the rest of the project]

?

**Comment by brucestephens** [comment]
I guess so. Maybe there are some other special cases (like github) that are worth doing (gitlab, for example), but maybe not. What you suggest is probably a good compromise: DTRT most of the time, and simple to understand how to change it.

**Comment by kgodwin** [comment]
http://[website-url]/[repo-name]/blob/master/[filename]#L[line-number]

Maybe the UrlToRepo should just support tokens then?

**Comment by brucestephens** [comment]
Dunno. Might be best to do something simple: so just cover cases 1 and 2 and forget about the
more annoying case?

And just leave a pointer to the relevant bit of javascript in the README, so people who want to can
easily find and hack it. (Or maybe this issue is sufficient, come to that.)

What I'd like is to have a collection of our local repositories, and they'll all map in the same way. So
actually changing the javascript would be easier than the config file (if it's necessary to configure
each repository separately). My guess is that that'll be fairly common. Maybe not, though.

Anyway, my guess is doing something simple (handle github and support local (ssh, etc.) repositories
by serving files) and seeing how people like it is probably best for now. It'll be less surprising than
the 404 that it produces now.

**Comment by MoriTanosuke** [comment]
When testing SVN support I noticed that in https://github.com/etsy/Hound/blob/master/pub/assets/js/hound.js#L292 there is a hardcoded reference to add *'/blob/master/'* to the URL. This does not work for SVN (I think it will only for for *git* repos :question:) and supporting multiple VCS via PR #39 breaks the link to the source files.

**Comment by jklein** [comment]
Thanks @MoriTanosuke, we should fix that. Can you open an issue, or fix it as part of your SVN PR?

**Comment by jklein** [comment]
@kellegous it seems like with your change we can update the README/example config and this issue will be able to be fully handled by the new functionality.

**Comment by jklein** [comment]
We now have a `url-pattern` directive that should solve this issue completely. Feel free to open a new one if you continue to have problems. You can see an example of how this works in [config-example.json](https://github.com/etsy/Hound/blob/master/config-example.json#L18-L24).
