### ISSUE TITLE
Private repo support?

### ISSUE THREAD

**Issue by pconerly** [etsy/Hound#2]
Is there private repo support? How does one configure it?

If not, it'd be a great feature to have!

@jdan suggested it on HN a few minutes ago.

**Comment by waynezhang** [comment]
Tried and private repo works fine.
But don't know how to set up a specify branch.

**Comment by jklein** [comment]
There's currently no out-of-the-box way to handle private repos. There are some workarounds suggested on the [HN thread](https://news.ycombinator.com/item?id=8957240). We would welcome a contribution to make support more official.

**Comment by jdan** [comment]
@jklein I would be happy with just specifying a local directory, to be honest - any particular reason why I can't do that?

**Comment by jklein** [comment]
No particular reason, we just built this for our use case and HTTP works well there. Hound also [polls for updates](src/hound/searcher/searcher.go#L154-L194) over HTTP and git pulls them down, so we would have to find a way to mimic that functionality if using a local directory.

**Comment by jdan** [comment]
Rad :+1: Thanks for the response

**Comment by technovangelist** [comment]
It seems to work just fine. I added a few private repos using the git@github.com:myorg/myrepo.git url and thats it.

**Comment by jklein** [comment]
I updated the README with the explanation of how you can use private repositories:

https://github.com/etsy/Hound#private-repositories

Since the issue with links in the SSH style URL case is documented in #19, I'm going to close this.

**Comment by jdan** [comment]
Thanks @jklein :)
