### ISSUE TITLE
No records returned when submitting search via HTTP GET 

### ISSUE THREAD

**Issue by bbaltz505** [etsy/hound#203]
If I submit a search via the Hound web UI and specify multiple repos, the query returns the correct matches. If I submit the query using the search URL, the multiple repos are not parsed correctly. See below:
Successful search via UI form:
Query string is:

> stats:fosho
> repos:rsa_example,sse_intrinsic_helper_classes
> rng::20
> q:dev
> files:
> i:nope

When submitting the same search via a direct URL:
http://<server>:6080/?q=dev&i=nope&files=&repos=rsa_example,sse_intrinsic_helper_classes

The Query string is:

> stats:fosho
> repos[]:rsa_example
> repos[]:sse_intrinsic_helper_classes
> rng::20
> q:dev
> i:nope
> files

I ended up commenting out lines in hound.js (line 63) and it works fine then:
```
//if (pair[1].indexOf(',') >= 0) {
//  params[decodeURIComponent(pair[0])] = pair[1].split(',');
//} else {
  params[decodeURIComponent(pair[0])] = decodeURIComponent(pair[1]);
//}
```

I'm not sure what else this affects though.
Thanks.
Brian Baltz

**Comment by kellegous** [comment]
Thanks, there have been a couple of things broken around the repo list for a while. I didn't realize the URLs were broken, though.
