### ISSUE TITLE
As of GitLab 8.6, cloning repos throws a http 500 error

### ISSUE THREAD

**Issue by alecsx** [etsy/hound#205]
I've tracked the issue down to the "git clone" command which uses an extra "--depth 1" argument. I think shallow clones are not allowed any longer. I've fixed this in my local environment by removing the depth option. I presume this will decrease the performance, however I haven't notice any major issues so far.

**Comment by muraiki** [comment]
I'm not experiencing any problems cloning using GitLab 8.8.3, so maybe this has been resolved in GitLab.

**Comment by zzhong** [comment]
I'm going to close this. Please re-open the issue if the problem comes back (or if it's still an issue with the current GitLab release).
