### ISSUE TITLE
Does Hound support multiple keywords?

### ISSUE THREAD

**Issue by bbaltz505** [etsy/hound#206]
Sorry, but I didn't see this mentioned anywhere. The default search seems to be single words or literal phrases. Is there a way to enter keywords so they for a compound search? I.e., 
"Dog Cat" gives files that contain "Dog" AND "Cat"

**Comment by dgryski** [comment]
Hound searches by regular expression.  Think of it as a super-powered "git-grep" that can cross multiple repositories very very quickly.

**Comment by bbaltz505** [comment]
Thanks.Yes, I love the speed and ability to span repos. I'm not clear on how to do more complex searches via the UI though. Whatever I enter in the keyword field seems to be interpreted literally as one ling string.

**Comment by dgryski** [comment]
Yes; hound will search for lines matching the regular expression in the input box.  It's not a general purpose keyword search engine.  For that, you would want ElasticSearch or some other full-text search engine.

**Comment by bbaltz505** [comment]
Thanks.
