### ISSUE TITLE
Hound freezes in Safari

### ISSUE THREAD

**Issue by vestimir** [etsy/Hound#21]
version: 8.0.2 (10600.2.5)

Beachballs in Safari :/ Works like a charm in Chrome.

**Comment by jklein** [comment]
Hmm, what exactly are you doing when this happens? I tested this on my Macbook Pro with the exact same Safari build that you have and it seems to work. Could it be an extension that is interacting with Hound?

**Comment by speg** [comment]
This happens to me (also in Safari) when I click the `clippy` icon. Presumably some flash thing that copies something to the clipboard?

**Comment by vestimir** [comment]
@jklein it freezes just by opening the URL. Only two extensions installed:
- JSON Formatter 1.1
- AdBlock 2.17

**Comment by jnunemaker** [comment]
Happens to me by just visiting hound in the browser the first time.

![screen shot 2015-01-29 at 10 09 20 am](https://cloud.githubusercontent.com/assets/235/5959780/e7222c20-a79e-11e4-85c4-5c28ce836f28.png)

The only plugin I have installed is 1password.

**Comment by jnunemaker** [comment]
It does not happen in chrome. I just checked.

**Comment by jklein** [comment]
I still can't seem to get this to happen. I think it might be flash related. Can you delete the ReactZeroClipboard.js include from index.tpl.html and try again?

**Comment by vestimir** [comment]
@jklein when I remove `ReactZeroClipboard.js` it doesn't freeze, but also it doesn't search at all - it just keeps the loading gif forever. I'll try to find the actual problem during the weekend.

**Comment by jklein** [comment]
Yeah that's partly my bad, you probably have to pull the ZeroClipboard stuff out of the JS file as well. You are likely getting JS errors now. That helps narrow it down though, I'm guessing it's related to the flash stuff that the clipboard does.

**Comment by vestimir** [comment]
@jklein yup I can confirm, that by removing this functionality it works like a charm. I also tried updating it to 2.2.0, but the result was the same. I guess it's freezing like this because of Safari's click to start strategy on flash elements.

**Comment by kellegous** [comment]
I vote we just get rid of flash and use a technique similar to what https://goo.gl/ uses. It just inlines an input with the text selected and says Ctrl-C/Cmd-C to copy.

**Comment by jklein** [comment]
@kellegous :+1:. The flash approach is causing a bunch of issues it seems, and I'd love to remove the flash dependency.

**Comment by vestimir** [comment]
@jklein how about making the file path a disabled input (+ a little bit of css/hover to make it nice) which upon click selects all the text for easy C+P. I can prepare a PR about this.

**Comment by jklein** [comment]
Yeah that would be great @vestimir, thanks

**Comment by jklein** [comment]
I just deleted all of the ReactZeroClipboard stuff and thus the flash dependency. This issue should be fixed, and if we want to add the ctrl+c prompt later that would be fairly easy to do. For now it's simple enough to click and drag to highlight and then hit ctrl+c.
