### ISSUE TITLE
i wrote a hound search plugin for hain

### ISSUE THREAD

**Issue by talarari** [etsy/hound#216]
check out this project:https://github.com/appetizermonster/hain
it's kind of like a spotlight search with tons of plugins.
i wrote a hound plugin to allow us to quickly search for code
https://github.com/talarari/hain-plugin-hound

you're welcome to install it from hain's package manager to check it out.
looks kind of like this:
.
![untitled](https://cloud.githubusercontent.com/assets/4973087/16195424/363d1e5c-3702-11e6-9213-838201fcd174.png)

**Comment by mrtazz** [comment]
This is awesome! Closing this issues since it's not actually an issue :)
