### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by michaelmior** [etsy/hound#22]
Have you considered adding support for syntax highlighting? This is complicated by the fact that each line is displayed separately. It seems like it would be much simpler to just show all the code inside a `<pre>` tag and then use something like [google-code-prettify](https://code.google.com/p/google-code-prettify/) to add line numbers and syntax highlighting. Then just apply the highlighting on the generated HTML using something like the [jQuery highlight plugin](http://bartaz.github.io/sandbox.js/jquery.highlight.html).

**Comment by cburroughs** [comment]
cgit allows results to be passed through arbitrary filter (ie pygyments).  This is generally flexible and works well, but does lead to some of the partial  vs full file situations.

**Comment by aidansteele** [comment]
An alternative (that may be ridiculous) is to use the Ace code editor in read-only mode: http://ace.c9.io/. As it sits entirely client-side it would require zero changes to the API and wouldn't have the complications that @cburroughs mentioned.

**Comment by belak** [comment]
There's also http://prismjs.com/
