### ISSUE TITLE
Local repo

### ISSUE THREAD

**Issue by speg** [etsy/Hound#23]
Does this support indexing local repositories?

The example config has a `url` key, but can I use, say `path` and set the value to a folder on my machine?

**Comment by kgodwin** [comment]
Use a file uri as the url, for example:

file:////home/kgodwin/Projects/dash

**Comment by speg** [comment]
Aha! Thanks @kgodwin that works.

**Comment by kgodwin** [comment]
Ya, it is basically a git clone command so just use the same URL/SSH text you'd normally use.
