### ISSUE TITLE
Hound add ssh key to docker image

### ISSUE THREAD

**Issue by zygisx** [etsy/hound#231]
When running `hound` in `docker` it is not possible to add ssh keys there to be able to index private github repositories.

If it possible then it is not documented anywhere.

**Comment by mbernabeu** [comment]
Try mount your folder ssh
docker run -d -p 6080:6080 --name hound -v $(pwd):/data  -v ~/.ssh:/root/.ssh etsy/hound

**Comment by zygisx** [comment]
Thanks that helped!

Closing this issue.

**Comment by ZhengHe-MD** [comment]
@mbernabeu run the command givens
```sh
panic: invalid character '"' after object key:value pair

goroutine 1 [running]:
main.main()
	/go/src/github.com/etsy/hound/cmds/houndd/main.go:129 +0x806
```

Do you have any ideas?

**Comment by ZhengHe-MD** [comment]
@mbernabeu never minds, my bug.
