### ISSUE TITLE
Index non-master branch

### ISSUE THREAD

**Issue by ge0rgi** [etsy/hound#234]
I just installed hound. I am pretty happy with it however I have the feeling that only the master branch is being indexed. I can't  find code which I have only in non-master branches. I also have some repos where the default branch in not master. Is there a way I could configure hound to index non-master branches and/or index a different branch instead of master?

**Comment by danielcb** [comment]
Hi,
[Here](https://github.com/etsy/hound/blob/master/vcs/git.go#L87) is the Clone function that gets executed the first time a new searcher gets created from the config:

```
cmd := exec.Command(
		"git",
		"clone",
		"--depth", "1",
		url,
		rep)
```

If you just want to add the possibility to fetch another branch _instead_ of master, that should be easy enough (git clone -b branch url). Adding all branches of a repo dynamically on each run and cleaning them up if they get removed is probably more difficult.

**Comment by ge0rgi** [comment]
Thanks I forked and added a branch property to the config file to specify the branch to index. It worked, however I had to change the driver interface to add a branch parameter to the clone method.

**Comment by dmsimard** [comment]
https://github.com/etsy/hound/pull/275 provides the ability to specify a git branch other than the hardcoded "master" and it works for us.
