### ISSUE TITLE
open_search.xml malformed

### ISSUE THREAD

**Issue by lheckemann** [etsy/hound#239]
The templating seems to substitute the `<` in the xml version declaration with `&lt;`. As a result, the search provider cannot be added in firefox.

Example: https://search.nix.gsc.io/open_search.xml

Adding the search provider fails in firefox with the cryptic error message
>Firefox could not download the search plugin from:
>https://search.nix.gsc.io/open_search.xml

**Comment by sahildua2305** [comment]
I'm facing the same issue with `open_search.xml` as well. I'm working a patch to fix this.
@stanistan feel free to assign this to me.

**Comment by grahamc** [comment]
FWIW future bug reviewers,  https://search.nix.gsc.io/open_search.xml works fine because I serve a static version of open_search.xml via nginx, instead of passing that request to Hound: https://github.com/grahamc/network/blob/master/zoidberg/default.nix#L155-L162

**Comment by stanistan** [comment]
@sahildua2305 I can't actually assign you using github's tools (probably due to some settings), but feel free to open a PR with the fix, assign me to review.
