### ISSUE TITLE
not a Rake fan

### ISSUE THREAD

**Issue by rbucker** [etsy/Hound#25]
I'm not a fan of using Rake as a replacement for a simple make or simple bash. But to illustrate a point similar to the go authors... using go to compile go. Here is a Gist that you are welcome to incorporate into your project.  I will adhere to whatever license you prefer:

https://gist.github.com/rbucker/2f362aeb0ddec24e8b8f

**Comment by jklein** [comment]
Now there is a makefile, and `go get` support is coming soon - going to close this.
