### ISSUE TITLE
Improve startup times - call newSearcher in parallel

### ISSUE THREAD

**Issue by bschlenk** [etsy/hound#250]
Within [MakeAll](https://github.com/etsy/hound/blob/d6a73ac4ff8a312b26a6cd892f1910fd3a460c31/searcher/searcher.go#L269), is there anything preventing the calls to [newSearcher](https://github.com/etsy/hound/blob/d6a73ac4ff8a312b26a6cd892f1910fd3a460c31/searcher/searcher.go#L369) from being done in parallel? With very large configurations it can take a few minutes for hound to start. At my job we are adding new repos all the time, so the startup time continues to get worse. Starting the searchers in parallel could greatly improve this startup time.

**Comment by sahildua2305** [comment]
This will indeed be a big improvement as that will bring the startup time down significantly. @kellegous do you foresee any obvious challenges with this? Asking you before I dive into code/implementation.

I had a look at `newSearcher` method that's mentioned in the issue description. And I saw we use `config.MaxConcurrentIndexers` field for parallelizing the re-indexers and not the first time indexers. What's your opinion?

**Comment by kellegous** [comment]
IIRC, this is just a matter of doing the work of fanning out the calls to `newSearcher` while honoring `config.MaxConcurrentIndexers` and then synchronizing the writes into the `searchers` map.

**Comment by sahildua2305** [comment]
Cool. I'd like to hack around this next then. Seems to be an interesting and significant enhancement.
