### ISSUE TITLE
Freeze when entering an invalid regex

### ISSUE THREAD

**Issue by jamime** [etsy/Hound#26]
When entering an invalid regex `(` it will freeze the tab.

**Edit:** Including an empty search term.

>Google Chrome
Version 40.0.2214.93 (64-bit)
OSX 10.9.5

**Comment by jklein** [comment]
Hmm, I'm trying to reproduce but I get the expected error message saying that the regex couldn't be parsed. I'm using Chrome Version 40.0.2214.93 (64-bit) as well, on OS X 10.10.2. Perhaps you have a Chrome extension that is interacting with Hound? Try it in a private browsing window and see if it works.

If you are still having issues, can you provide a little more info? Do you have anything checked or filled out under advanced?

**Comment by jamime** [comment]
Just ran it in a private browser.
> ./bin/houndd
2015/01/29 15:34:51 Searcher started for **removed**
2015/01/29 15:34:52 Searcher started for **removed**
2015/01/29 15:34:58 merge 0 files + mem
2015/01/29 15:34:58 18771141 data bytes, 3299207 index bytes
2015/01/29 15:34:58 All indexes built, running server at http://localhost:6080...

* Put cursor in input
* Press enter

Tab will lock
`$ top` shows that Google Chrome Helper is using %CPU 120+


It actually locks up then re-enables on regular searches too. 

I noticed in the console

>  You are using the in-browser JSX transformer. Be sure to precompile your JSX for production - http://facebook.github.io/react/docs/tooling-integration.html#jsx

A potential cause?

**Comment by jklein** [comment]
Yeah that could be it @jamime, can you try running the binary with the --prod flag? So just `./bin/houndd --prod`. That will compile the JS and take the JSX transformer piece out of the picture.

**Comment by jamime** [comment]
@jklein `./bin/houndd --prod` did not fix. I can reproduce on my MacBook too. An empty search term will instantly crash both Chrome and Safari.

* OSX 10.10.1
* go version go1.4.1 darwin/amd64
* react-tools@0.12.2 /usr/local/lib/node_modules/react-tools
* jstransform@8.2.0 (base62@0.1.1, esprima-fb@8001.1001.0-dev-harmony-fb, source-map@0.1.31)
*  commoner@0.10.1 (private@0.1.6, commander@2.5.1, graceful-fs@3.0.5, install@0.1.8, q@1.1.2, iconv-lite@0.4.6, mkdirp@0.5.0, recast@0.9.15, glob@4.2.2)
* Google Chrome 40.0.2214.94
* Safari 8.0.2 (10600.2.5)

Please let me know if there is anything I can do to help.

**Comment by jklein** [comment]
Okay, more things to try - can you just change your config.json to only have one repo, maybe jQuery or something? I want to see if it's related in some way to that. Here's a config.json you could use:

```
{
    "dbpath" : "data",
    "repos" : {
        "jQuery" : {
            "url" : "https://github.com/jquery/jquery.git"
        }
    }
}
```

**Comment by jamime** [comment]
> $ ./bin/houndd --prod
2015/01/30 23:02:26 Searcher started for jQuery
2015/01/30 23:06:16 merge 0 files + mem
2015/01/30 23:06:16 1524338 data bytes, 777610 index bytes
2015/01/30 23:06:16 All indexes built, running server at http://localhost:6080...
 
An empty search term gives me:
> ERROR:search exceeds limit on matches: 5000

I thought I would try accessing the API directly and it responds successfully for my private repo.

**Comment by jamime** [comment]
Interestingly after reducing the size of the jQuery repo (deleting files from `Hound/data/jQuery` and removing the cache directory) and rebooting the server. The empty search term again crashes the tab.

**Comment by jklein** [comment]
Most of the crashes we have seen are related to the flash file for the "copy" functionality. Can you remove that from index.tpl.html and also pull out the ZeroClipboard stuff from `pub/assets/js/hound.js` and see if that stops the crashes?

**Comment by jamime** [comment]
Removed `<script src="assets/js/ReactZeroClipboard.js"></script>` from `index.tpl.html` and 
````javascript
<ReactZeroClipboard className="copy-path-container" text={match.Filename}>
  <button className="copy-path-btn">
    <span className="octicon octicon-clippy"></span> 
  </button>
</ReactZeroClipboard>
```
from `pub/assets/js/hound.js`

Running the jQuery repo with some files removed so we don't hit the api limit.

>$ ./bin/houndd --prod
2015/02/01 17:26:04 Searcher started for jQuery
2015/02/01 17:26:06 All indexes built, running server at http://localhost:6080...

Search term `a` works fine. Empty search still crashes.

**Comment by jklein** [comment]
I'm at a bit of a loss here, I can't reproduce and we haven't heard of this issue from anyone else (aside from flash related issues). Is there a crash dump or crash report? I think we're going to need a little more legwork on your side to figure this out, since it appears to be something specific to your environment.

**Comment by jamime** [comment]
I'll try and get some more diagnostic information and full steps to reproduce from a fresh install. Same problem on two separate machines.

**Comment by jklein** [comment]
Thanks @jamime - also make sure you pull in all new changes since I completely removed the dependency on flash, which was causing some crashes.

**Comment by jamime** [comment]
@jklein started fresh once again and it works perfectly. I'll reproduce on my other machine and let you know if I find anything. Thank you!
