### ISSUE TITLE
Editor integration?

### ISSUE THREAD

**Issue by vext01** [etsy/Hound#28]
Hi again,

Do you plan to integrate hound into editors? Currently you have to leave my editor, visit a web page, and when you click a hit, you are taken to a github page. It would be nice if users could harness hound in their editor of choice: vim/emacs/eclipse/whatever.

I am a vim user, so I imagine a use case where I can type `:hound <search_term>`, then a pane would show hits, which I could select from a list to open them as buffers. The ack vim plugin (which is what I currently use) works like this.

I'm not sure how you would account for local edits though.

Quite an ambitious proposal I know, but have you thought about it? Maybe it is too much effort...

Thanks

**Comment by jklein** [comment]
There is already a Sublime Text plugin: https://github.com/bgreenlee/SublimeHound

Feel free to make plugins for other editors as well. We might get to it at some point, but it's not high on the list. If you make one we would be happy to link to it in the README.

**Comment by jklein** [comment]
I'm actually going to close this, since I think editor extensions/plugins should live in their own repo and will likely be created/supported by other people.
