### ISSUE TITLE
Houndd crashes on empty repositories

### ISSUE THREAD

**Issue by KLINGTdotNET** [etsy/Hound#33]
One of my github projects is an empty repository at the moment. The `houndd/main.go` crashes every time it tries to scan it: 

```sh
go run src/hound/cmds/houndd/main.go                                                                                                                                (no jobs) [master]  Week 05 29.01.15 13:53
2015/01/29 13:54:00 Searcher started for gol
panic: exit status 1

goroutine 1 [running]:
main.main()
	/tmp/Hound/src/hound/cmds/houndd/main.go:304 +0x5a6
exit status 2
```

Please integrate a check for empty repositories.

**Comment by jklein** [comment]
Yeah someone else mentioned this as well. This is a bug, thanks for reporting it.

**Comment by KLINGTdotNET** [comment]
That's what I call a fast reponse :100:

**Comment by KLINGTdotNET** [comment]
#36 seems to work, no more crashes on empty repos!
:+1:
