### ISSUE TITLE
Houndd errors after rebuilding index

### ISSUE THREAD

**Issue by avadhutp** [etsy/Hound#34]
I ran hound using 
```go run src/hound/cmds/houndd/main.go```

Works fine for a while. Then, I see this in my console—
```bash
2015/01/29 14:50:23 Rebuilding fs-scoring for efa7db02762ad04355539f65b1b7a8e7e33b9bbe
2015/01/29 14:50:26 merge 0 files + mem
2015/01/29 14:50:26 2470307 data bytes, 478302 index bytes
HeapInUse = 4.84
HeapIdle  = 473.31
```

And after that, searching for anything gives messages like these—
```
ERROR:open /home/aphatarpekar/setups/Hound/data/questionnaire-service-50fab2c00d1251d2b020a4776de59359405285aa/raw/pom.xml: no such file or directory
```

**Comment by Napolskih** [comment]
:+1:

**Comment by jklein** [comment]
@avadhutp do you happen to have a repo called just "questionnaire"? We fixed a bug related to that recently.

**Comment by avadhutp** [comment]
@jklein : 
1. We do. 
1. Also, we had a bunch of repos that would face problems due to the scenario described by @adstephenson in #14 
1. Pulled the latest version and it seems to have fixed all of it.
