### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by wildthink** [etsy/Hound#37]
Would be great to support a RESTful API to support native front ends.

**Comment by jklein** [comment]
That's what the Go service provides...it can be used as a standalone API for alternate clients, e.g. the [Sublime Text plugin](https://github.com/bgreenlee/SublimeHound). What more are you looking for?

**Comment by jklein** [comment]
Going to close this since I think we have everything you need. Feel free to re-open if there is missing functionality that you want.
