### ISSUE TITLE
All links are 404s

### ISSUE THREAD

**Issue by offby1** [etsy/Hound#4]
Here's an example:

```
http://localhost:6080/git@github.com:Internetworkexpert/Members-Dash/blob/master/assets/bower_components/bootstrap/less/type.less#L114
```

Naturally you won't be able to see the original on github, because it's private.

**Comment by jklein** [comment]
It looks like you are probably using ssh style URLs in your config file instead of HTTP URLs. Can you paste a copy of your config?

**Comment by mydimension** [comment]
Same issue with an internal repo which is only accessible via ssh

**Comment by jklein** [comment]
Yeah, currently Hound only supports accessing repos over HTTP. I'm going to close this issue for now, and I'll open one for supporting ssh.

**Comment by mydimension** [comment]
it indexed the repo just fine, and even see it cloned in it's data directory. just seems to be viewing in the web interface that doesn't work

**Comment by offby1** [comment]
@jklein You are correct; the URLs are for ssh.  Ideally, the docs would say "please don't do that", and even more importantly: I'd get a clear error message (either when starting the server, or when clicking one of those links) saying "sorry, SSH URLs aren't supported".

**Comment by jklein** [comment]
Yeah we should just fix this though. Check out #19 for discussion.
