### ISSUE TITLE
Work with local repos (no clone)

### ISSUE THREAD

**Issue by gerco** [etsy/Hound#43]
Enhancement suggestion:
I would like Hound to work with repos that are already on my server, without cloning them first. This is for an in-house repo hosting server, for example.

**Comment by halbtuerke** [comment]
:+1:

**Comment by jklein** [comment]
This should already work - either using the file:// protocol as the URL in `config.json`, or if you want Hound to manage the repos and keep them updated you can just change the dbpath in `config.json` to point to the parent folder of your existing repos. As long as the repo names in the config match the folders on disk, Hound should work without issue.

If you are trying this and having problems, feel free to open another issue with specifics. Thanks!
