### ISSUE TITLE
Backend pointing to the existing local repositories instead of a git clone

### ISSUE THREAD

**Issue by cliren** [etsy/Hound#54]
Two questions:

1. Can the config.json be pointed to local path instead of a git location? For example if I deploy Hound on a stash repo box (which has the all source code) and point the config so that Hound's data/ directory symlinks to the stash repo. The config would looks something like below:

config.json

{
    "dbpath" : "data",
    "repo-type": "local",
    "repos" : {
        "SomeRepo" : {
            "url" : "~/MyRepositories/SomeRepo"
        },
        "AnotherRepo" : {
             "url" : "~/MyRepositories/AnotherRepo"
        }
    }
}

Add symlink
~/Hound/data symlinks to ~/MyRepositories/

2. Does it auto index when new code is pushed to the repository?

**Comment by jklein** [comment]
1. You can index local folders using the file:// protocol
2. If you are using a git URL the Hound server will poll for updates and reindex when a new version is detected.

**Comment by cliren** [comment]
Good to know, thanks!
