### ISSUE TITLE
Support simple query language

### ISSUE THREAD

**Issue by MoriTanosuke** [etsy/Hound#57]
It would be nice if Hound supports a simple query language like *"firstTerm !secondTerm"* (search files including "firstTerm", but not "secondTerm"). Narrowing down a search with the regex file path works fine, but sometimes I want to search for specific filenames and match files that I have not yet modified (for example, adding a plugin to several POMs). 

Having a simple query like the one above combined with the regex file path would allow me to search for those files. Using *AND*, *OR*, *NOR*, *XOR* would also be possible.

Do you think this is feasible and in line with the direction you want Hound to move?

**Comment by jklein** [comment]
I feel like regular expression searches satisfy the vast majority of potential use cases, so I'm not a huge fan of this b/c of the extra complexity, but let's see what @kellegous thinks.

**Comment by kellegous** [comment]
I thought a bit about whether we needed support for boolean expressions outside of regexp, but I never found a real use case. @MoriTanosuke, can you describe your use case further.

**Comment by MoriTanosuke** [comment]
After using Hound a couple of days I think the provided features are enough for my usecase. Initially I though searching for files that have the searchterms *"my-dependency AND NOT an-incompatible-dependency"* would be nice, but I never really searched for it.

I'm now using Hound more like an easy-to-use searchengine so that I don't have to keep all the projects open in my IDE. If I don't find what I'm looking for with simple search terms, I have to think a bit more about what I am really looking for anyways.

For me, you can close this issue. :closed_lock_with_key:

**Comment by jklein** [comment]
Thanks @MoriTanosuke, we appreciate you being thoughtful about this!
