### ISSUE TITLE
cannot clone local mercurial (hg) repository

### ISSUE THREAD

**Issue by afriza** [etsy/Hound#59]
2015/02/03 14:30:04 Searcher started for ABC-Project
    2015/02/03 14:30:04 Failed to clone file://abc/project, see output below
    Cloning into 'ABC-Project'...
    fatal: '/abc/project' does not appear to be a git repository
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.
    Continuing...
    2015/02/03 14:30:04 Some repos failed to index, see output above
    2015/02/03 14:30:04 running server at http://localhost:6080...

The folder exists and I have the access right since I'm running it as root.. It's just that it is local `mercurial` repo instead of `git`.. I am using commit d2c1d98deb169f2539668d6992207a9e9d83b8dd

**Comment by belak** [comment]
The config file defaults to git for the VCS, so for a mercurial repo you have to specify "vcs": "hg"

**Comment by jklein** [comment]
What @belak said, closing this.

**Comment by afriza** [comment]
Hello, thanks, it works.. but maybe should be mentioned in the readme?

**Comment by jklein** [comment]
Yeah I'll add it, good call.
