### ISSUE TITLE
make failed on src/hound/index/grep.go

### ISSUE THREAD

**Issue by redbrain17** [etsy/Hound#66]
After clone your repo  and configure the config file I run make and it stops with that error on Ubuntu 12.04

make
GOPATH=`pwd` go build -o bin/houndd src/hound/cmds/houndd/main.go
hound/index
src/hound/index/grep.go:64: function ends without a return statement
src/hound/index/grep.go:137: function ends without a return statement
make: *** [bin/houndd] Fehler 2

**Comment by jklein** [comment]
Can you tell us what version of Go you are using? The output of `go version` would be ideal.

**Comment by redbrain17** [comment]
I' am using

$ go version
go version go1

is that suffiant to run Hound?

**Comment by jklein** [comment]
No, we only support Go 1.3+, and if it just says go1 I assume that's 1.0. Try upgrading and if you still experience an issue you can reopen this issue.
