### ISSUE TITLE
Please make it go get-able

### ISSUE THREAD

**Issue by psankar** [etsy/Hound#7]
Please make it go get-able

**Comment by pierrre** [comment]
```
Set your GOPATH: export GOPATH=`pwd`
```
is wrong.

**Comment by shoenig** [comment]
Yeah, requiring Rake(!) for a Go project is insane

**Comment by kellegous** [comment]
This is definitely on the list. The only blocker as been figuring out what to do with the web assets that Hound needs for the UI. My current plan is to support two modes of building:

(1) When installing with `go get` hound will continue to depend on the src directory that is cloned during the build process.

(2) Make build will aim to build a more stand-alone version where the assets are bundled in some form.

The command line tool may already be go-gettable, but I haven't checked in a while and it's certainly not useful without a server.

**Comment by pierrre** [comment]
https://github.com/jteeuwen/go-bindata and commit the generated .go files?

**Comment by sriniprash** [comment]
https://github.com/mjibson/esc interfaces with net/http

**Comment by caglar10ur** [comment]
In the meantime what about providing a Makefile like following? Rake is giving hard time to the distros with older ruby versions (undefined method `absolute_path' for File:Class)

```
all:
	@GOPATH=`pwd` go build -o bin/houndd src/hound/cmds/houndd/main.go
	@GOPATH=`pwd` go build -o bin/hound -ldflags "-X main.defaultHost ${HOST-localhost:6080}" src/hound/cmds/hound/*.go

.PHONY: all
```

**Comment by kellegous** [comment]
I put up a PR to switch to a Makefile until this is all go-gettable https://github.com/etsy/Hound/pull/44

**Comment by belak** [comment]
Do the maintainers have any preferences for this? Something like go-bindata and a Makefile to turn the assets into go files might be the best option.

**Comment by caglar10ur** [comment]
I suggest taking a look at https://github.com/golang/tools/blob/master/godoc/static/makestatic.go as well. This is what godoc.org uses.

**Comment by matrixik** [comment]
Or use https://github.com/GeertJohan/go.rice and it will work with `go get` without need for commiting generated files.

**Comment by caglar10ur** [comment]
@matrixik but with go.rice, one cannot distribute a binary only file as it requires source code to be available. 

To me, godoc is way simpler but of course YMMV. 

* Put your resources into https://github.com/golang/tools/blob/master/godoc/static/makestatic.go, 
* Create a file like 
https://github.com/golang/tools/blob/master/godoc/static/gen.go so that one can use "go generate" 
* Use https://godoc.org/golang.org/x/tools/godoc/vfs + https://godoc.org/golang.org/x/tools/godoc/vfs/httpfs to serve that over http and https://godoc.org/golang.org/x/tools/godoc/vfs/mapfs over fs.

**Comment by matrixik** [comment]
@caglar10ur go.rice allow you to do both things at once:
> During development go.rice will load required files directly from disk. Upon deployment it is easy to add all resource files to a executable using the rice tool, without changing the source code for your package. go.rice provides several methods to add resources to a binary.

https://github.com/GeertJohan/go.rice#what-does-it-do
https://github.com/GeertJohan/go.rice#tool-usage

**Comment by rhyolight** [comment]
:+1: because I want to deploy to Heroku and I can't. :frowning:
