### ISSUE TITLE
Make code.google.org/p/codereply sync up with published version

### ISSUE THREAD

**Issue by belak** [etsy/Hound#71]
This is related to #7 in that when I removed the copy of code.google.org/p/codesearch, everything broke as the version that's public doesn't have `*Index.Close()`

Should this library be forked or something like that so we can make the project go-gettable?

**Comment by kellegous** [comment]
Thanks for looking into this. My plan was to move that out of code.google.com and into hound proper. I'll find a way to ask the golang folks if they have any interest in our changes. I'm assuming they don't. We definitely don't want to run Hound with the current codesearch code as it'll leak tons of address space. BTW, I'm totally under the gun for a few more days and then I hope to get a break to take care of some of these big issues.

**Comment by jklein** [comment]
@kellegous it looks like your commit fixed this?

**Comment by belak** [comment]
What's the status of this?

**Comment by kellegous** [comment]
Our fork of code.google.com/p/codesearch has been moved into hound/codesearch.
