### ISSUE TITLE
Support for Stash (and other) URLs

### ISSUE THREAD

**Issue by paulwellnerbou** [etsy/Hound#75]
Is there a way to configure the format/pattern of the URL where the results are linked to? It works fine with gitlab and github, but with stash, another format is expected:

    https://mystash.tld/projects/PROJECT/repos/REPO/browse/common/src/main/...

**Comment by platan** [comment]
:+1:

**Comment by sveisvei** [comment]
:+1:

**Comment by platan** [comment]
I've prepered scrip for creating Hound config file based on Stash reposiories: https://gist.github.com/platan/8723c837c5322172c983

**Comment by paulwellnerbou** [comment]
@platan Great, I used a dirty shell script for this. The new url pattern property is not part of this script yet, right? So the urls in the search results won't work.

**Comment by platan** [comment]
@paulwellnerbou I've modified Hound in my fork to support only Stash repositories, so URLs works for me :-) After merging url pattern property feature into master I'm going to update my script.

**Comment by platan** [comment]
New version of the script (https://gist.github.com/platan/8723c837c5322172c983) for creating Hound config file based on public Stash reposiories supports URL pattern. Example output:
```
{
    "repos": {
        "PROJ2-repo4": {
            "url": "http://localhost:7990/scm/proj2/repo4.git", 
            "url-pattern": {
                "base-url": "http://localhost:7990/projects/PROJ2/repos/repo4/browse/{path}{anchor}", 
                "anchor": "#{line}"
            }
        }
    }, 
    "dbpath": "data"
}
```

**Comment by jklein** [comment]
This is now supported with the [url-pattern directive](https://github.com/etsy/Hound/blob/master/config-example.json#L37-L43) that has been merged into core.
